id: I1C9BCB08
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:17:55+00:00'
last_modified: '2022-06-07T17:20:05.329218+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC265
  title: རྫས་འགྱུར་རིག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7849':
      image_group_id: I2PD17766
      title: ''
      total_pages: 682
      order: 1
      base_file: 7849.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
