id: P003067
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:38:12.946635
source_metadata:
  id: bdr:W1AC265
  title: རྫས་འགྱུར་རིག་པ།
  author: ''
  volumes:
    69681abdd951410eb782019fefdfc7ec:
      image_group_id: I2PD17766
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
